spring.application.name=metamapa
# CronJob for collection refresh (every hour)
collection.refresh.cron=0 0 * * * *
# Agregation service port
server.port=8080
# Agregation service URL
aggregation-service.url=http://localhost:8080