spring.application.name=metamapa
# CronJob for collection refresh (every hour)
collection.refresh.cron=0 0 * * * *
# BaseURLs for the source modules
dynamic-source.api.base-url=http://localhost:8081
proxy-source.api.base-url=http://localhost:8082
static-source.api.base-url=http://localhost:8083

server.port=8080

