spring.application.name=metamapa
# CronJob for collection refresh (every hour)
collection.refresh.cron=0 0 * * * *
# BaseURLs for the source modules
proxy-source.api.base-url=path
static-source.api.base-url=path
dynamic-source.api.base-url=path
