# NaturalDisastersAPI Configuration
natural-disasters.api.base-url=https://api-ddsi.disilab.ar/public
natural-disasters.api.credentials.email=ddsi@gmail.com
natural-disasters.api.credentials.password=ddsi2025*
server.port=8082
thread.count=16
